### ISSUE TITLE
When I run the "Pull" command, something strange happened

### ISSUE THREAD

**Issue by aoout** [oscarspalk/obsidian-git-sync#2]
as a example, in my value:

```
- A
  - B
  - C
```

when I run the "pull" comand, in my value:

```
- A
  - B
  - C
- A/B
- A/C
```

I don't know why. I restart the obsidian, and it juse back to normal.

**Comment by oscarspalk** [comment]
So your folder structure turns to
```
- A
   - B
   - C
- A/B
- A/C
```
If that is the case, I can't reproduce it, maybe I misunderstood something.
